button and topbar ui updates
eoscostarica/evodex pull request #151
Opened 2020-09-02 07:31 UTC by pinkhoodie

#### CheckList
- [ ] Updated button fontweight
- [ ] Removed sub header of topbar's background
- [ ] Shortened width of inputs in wide screen and removed borderBottom

2020-09-03 15:43 UTC, tetogomez approved these changes
LGTM

2020-09-04 00:44 UTC, xavier506 commented on src/routes/Evodex/BackLayer/Exchange/ExchangeBackLayer.js
> +    width: '70%',
why reduce the width to 70% ? 

The exchange page looks off center and is not consistent 
![image](https://user-images.githubusercontent.com/5632966/92186898-71408880-ee15-11ea-93a6-1780b27d0864.png)

https://deploy-preview-151--evodex.netlify.app/exchange

2020-09-04 01:01 UTC, xavier506 requested changes
please see comments and resolve merge conflicts

2020-09-04 01:07 UTC, xavier506 commented on src/components/InputTextAndSelect/InputTextAndSelect.js
> +    borderBottom: '0px solid rgba(255,255,255,0.38)',
The bottom border was in the original wireframe, why should we remove it?

2020-09-06 06:11 UTC, closed without merging